//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circuitos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circuitos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Circuitos()
        {
            this.Fotos = new HashSet<Fotos>();
        }
    
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Coordenadas { get; set; }
        public string UrlWiki { get; set; }
        public string UrlCircuito { get; set; }
        public Nullable<System.DateTime> Inauguracion { get; set; }
        public Nullable<int> IdLocalidad { get; set; }
    
        public virtual Localidades Localidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fotos> Fotos { get; set; }
    }
}
